### ISSUE TITLE
Max Ram incorrect in Technical Reference Manual?

### ISSUE THREAD

**Issue by Spacefish** [milkv-pioneer/hardware#1]
https://github.com/milkv-pioneer/hardware/blob/main/SG2042-TRM.pdf
mentions:

`Max 256GiB DRAM with singe chip, 256GiB with dual chips system`
in section 1.1 Key features...
Shouldn´t this be:
`Max 128GiB DRAM with single chip, 256GiB with dual chips system`?

**Comment by jonathancross** [comment]
@hokamilkv ?

**Comment by hokamilkv** [comment]
We have only tried 4x32GB memory sticks on the Pioneer board. The reason why it's not labeled as supporting up to 256GB is because we didn't find a suitable 64GB memory stick. If you have tested other models of memory sticks, you can update to our [ddr support list](https://github.com/milkv-pioneer/pioneer-files/blob/main/hardware/sg2042_ddr_support_list.md). @Spacefish @jonathancross
